DROP DATABASE IF EXISTS proyecto2;
CREATE DATABASE IF NOT EXISTS proyecto2;
USE proyecto2;


CREATE TABLE IF NOT EXISTS mensaje (
	id_mensaje INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	contenido VARCHAR(500),
	fecha DATETIME,
	id_usuario INT NOT NULL,
	id_amigo INT NOT NULL,
	
	FOREIGN KEY (id_usuario) REFERENCES usuarios (id) ON DELETE CASCADE,
    FOREIGN KEY (id_amigo) REFERENCES usuarios (id) ON DELETE CASCADE
);



